### ISSUE TITLE
환경 구성 진행 중 발생한 이슈

### ISSUE THREAD

**Issue by EstherCho-7** [DE32FinalTeam2/FourthProject#9]
Readme에 적힌 대로 환경 구성 진행 시, streamlit의 스케일 인아웃 현황에서 plotly 모듈이 없다는 에러와 함께 사진과 같은 문제 발생

![image](https://github.com/user-attachments/assets/168e27cb-8714-4351-b6b2-7f0e5eaabec9)

**Comment by DONGUK777** [comment]
- [x] 환경 구성 진행 중 발생한 이슈 처리
---
![image](https://github.com/user-attachments/assets/59e57f4f-132e-401e-a5bd-a5741781a818)
- plotly 의존성 추가
![image](https://github.com/user-attachments/assets/47b04230-4e16-4967-9fb6-b25b4c624e81)

- push 했으니, pull하시고 pip install 하시고 테스트 부탁드립니다

**Comment by EstherCho-7** [comment]
![image](https://github.com/user-attachments/assets/1546e56c-dfda-48bc-9d8e-63125b909367)

Test OK

**Comment by DONGUK777** [comment]
고생하셨습니다~

**Comment by EstherCho-7** [comment]
감사합니다
